import { createClient, type PostgrestError, type SupabaseClient } from '@supabase/supabase-js';
// Generated by `npm run db:types` into server/src/ and shared through the
// `@db-types` path in tsconfig.json. Type-only, so Vite never bundles it.
import type { Database } from '@db-types';
import { env, envError } from '../env';

if (envError) throw new Error(envError);

export type Db = SupabaseClient<Database>;
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type Views<T extends keyof Database['public']['Views']> = Database['public']['Views'][T]['Row'];

/**
 * The browser's Supabase client. Queries run as the signed-in user, so
 * row-level security limits them to that user's shops.
 */
export const supabase: Db = createClient<Database>(env.supabaseUrl, env.supabaseAnonKey);

/** Returns the data from a supabase-js result, or throws its error. */
export function unwrap<T>(result: { data: T | null; error: PostgrestError | null }): T {
  if (result.error) throw new Error(result.error.message);
  if (result.data === null) throw new Error('No data returned');
  return result.data;
}

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** Ids come from the URL; anything that isn't a uuid can't match a row. */
export function isUuid(value: string | undefined): value is string {
  return !!value && UUID.test(value);
}
